# Generated by Django 5.2 on 2025-04-21 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                (
                    "publication_year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(2025),
                        ],
                    ),
                ),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                ("stock", models.IntegerField(default=1)),
                ("available", models.IntegerField(default=1)),
                (
                    "cover_pic",
                    models.ImageField(blank=True, null=True, upload_to="book_covers/"),
                ),
                ("genre", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "book",
                "ordering": ["title"],
            },
        ),
    ]
