# Generated by Django 5.2 on 2025-04-24 16:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0002_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_period_days", models.PositiveIntegerField(default=14)),
                (
                    "charge_per_day",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
                ),
                (
                    "max_outstanding_debt",
                    models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
                ),
            ],
            options={
                "verbose_name": "Settings",
                "verbose_name_plural": "Settings",
                "db_table": "settings",
            },
        ),
        migrations.AlterField(
            model_name="member",
            name="joined_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("ISSUE", "Issue"), ("RETURN", "Return")],
                        max_length=10,
                    ),
                ),
                ("issue_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("return_date", models.DateTimeField(blank=True, null=True)),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="libraryapp.book",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="libraryapp.member",
                    ),
                ),
            ],
            options={
                "db_table": "transaction",
                "ordering": ["-issue_date"],
            },
        ),
    ]
